In [1]:
import pandas as pd
import numpy as np
data ={"Name":["Prince","Aman","Nitish","Priyanka","Nancy"],
      "Age":["33","22","45","55","52"],
       "Percentage":["80","89","90","91","98"]}
df=pd.DataFrame(data)
df

       Name Age Percentage
0    Prince  33         80
1      Aman  22         89
2    Nitish  45         90
3  Priyanka  55         91
4     Nancy  52         98

In [4]:
import pandas as pd
import numpy as np
data={"Name":[ "Prince","Amit","Suresh","Dhoni"],
"Age": ["33","99","56","87"],
"Percentage":["90","89","67","56"]}
df=pd.DataFrame(data)
df

     Name Age Percentage
0  Prince  33         90
1    Amit  99         89
2  Suresh  56         67
3   Dhoni  87         56